# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.srcs/sources_1/bd/ZModem_top/ip/ZModem_top_Constant_Inputs_0_0/ZModem_top_Constant_Inputs_0_0.xci
# IP: The module: 'ZModem_top_Constant_Inputs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_Constant_Inputs_0_0/src/ZModem_constrs.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZModem_top_Constant_Inputs_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.srcs/sources_1/bd/ZModem_top/ip/ZModem_top_Constant_Inputs_0_0/ZModem_top_Constant_Inputs_0_0.xci
# IP: The module: 'ZModem_top_Constant_Inputs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_Constant_Inputs_0_0/src/ZModem_constrs.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZModem_top_Constant_Inputs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
