# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.srcs/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/ZModem_top_adc_interface_0_0.xci
# IP: The module: 'ZModem_top_adc_interface_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/src/xadc_wiz_0/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/src/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/src/xadc_wiz_0/xadc_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: C:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.srcs/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/ZModem_top_adc_interface_0_0.xci
# IP: The module: 'ZModem_top_adc_interface_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/src/xadc_wiz_0/xadc_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/src/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/src/xadc_wiz_0/xadc_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
