# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZModem_constrs.xdc

# Block Designs: bd/ZModem_top/ZModem_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top || ORIG_REF_NAME==ZModem_top} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_uart_rx_0_0/ZModem_top_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_uart_rx_0_0 || ORIG_REF_NAME==ZModem_top_uart_rx_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_uart_tx_0_0/ZModem_top_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_uart_tx_0_0 || ORIG_REF_NAME==ZModem_top_uart_tx_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_adc_interface_0_0/ZModem_top_adc_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_adc_interface_0_0 || ORIG_REF_NAME==ZModem_top_adc_interface_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_aes_decrypt_0_0/ZModem_top_aes_decrypt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_aes_decrypt_0_0 || ORIG_REF_NAME==ZModem_top_aes_decrypt_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_aes_encrypt_0_0/ZModem_top_aes_encrypt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_aes_encrypt_0_0 || ORIG_REF_NAME==ZModem_top_aes_encrypt_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_byte_batcher_0_0/ZModem_top_byte_batcher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_byte_batcher_0_0 || ORIG_REF_NAME==ZModem_top_byte_batcher_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_byte_unpacker_0_0/ZModem_top_byte_unpacker_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_byte_unpacker_0_0 || ORIG_REF_NAME==ZModem_top_byte_unpacker_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_symbol_serializer_0_0/ZModem_top_symbol_serializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_symbol_serializer_0_0 || ORIG_REF_NAME==ZModem_top_symbol_serializer_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_symbol_deserializer_0_0/ZModem_top_symbol_deserializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_symbol_deserializer_0_0 || ORIG_REF_NAME==ZModem_top_symbol_deserializer_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_qpsk_modulator_0_0/ZModem_top_qpsk_modulator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_qpsk_modulator_0_0 || ORIG_REF_NAME==ZModem_top_qpsk_modulator_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_qpsk_demodulator_0_0/ZModem_top_qpsk_demodulator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_qpsk_demodulator_0_0 || ORIG_REF_NAME==ZModem_top_qpsk_demodulator_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_processing_system7_0_0/ZModem_top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_processing_system7_0_0 || ORIG_REF_NAME==ZModem_top_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_rst_ps7_0_100M_0/ZModem_top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZModem_top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ZModem_top/ip/ZModem_top_Constant_Inputs_0_0/ZModem_top_Constant_Inputs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZModem_top_Constant_Inputs_0_0 || ORIG_REF_NAME==ZModem_top_Constant_Inputs_0_0} -quiet] -quiet

# XDC: c:/work/github/Z-Modem/Z-Modem-PL/Z-Modem-PL.gen/sources_1/bd/ZModem_top/ZModem_top_ooc.xdc
